model:
    arch: gated_mwcnn
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 256 # 512
    img_cols: 512 # 1024
    #path: /datasets/cityscapes/
    path: /data/rul002/waveletCNN/cityscapes
    # /private/home/meetshah/misc_code/ps/data/VOCdevkit/VOC2012/
training:
    train_iters: 85000
    batch_size: 8
    val_interval: 500
    print_interval: 25
    n_workers: 16
    optimizer:
        name: 'sgd'
        lr: 1.0e-9 #1.0e-10
        weight_decay: 0.0005
        momentum: 0.99
        #optimizer:
        # lr: 1.0e-4
    l_rate: 1.0e-3 #1.0e-4
    l_schedule:
    loss:
        name: 'multi_scale_cross_entropy' #'cross_entropy'
        size_average: False
    lr_schedule:
    momentum: 0.99
    weight_decay: 0.0005
#     resume: gated_mwcnn_cityscapes_best_model.pkl
    resume: /home/rul002/waveletCNN/semseg_pytorch/runs/gated_mwcnn_cityscapes/fixed_run3_1/gated_mwcnn_cityscapes_best_model.pkl
    visdom: False
