model:
    arch: segnet
data:
    dataset: cityscapes
    train_split: train
    val_split: val
    img_rows: 256 # 512
    img_cols: 512 # 1024
    #path: /datasets/cityscapes/
    path: /data/rul002/waveletCNN/cityscapes
    # /private/home/meetshah/misc_code/ps/data/VOCdevkit/VOC2012/
training:
    train_iters: 85000
    batch_size: 4
    val_interval: 500
    print_interval: 25
    n_workers: 16
    optimizer:
        name: 'sgd'
        lr: 1.0e-9
        weight_decay: 0.0005
        momentum: 0.99
        #optimizer:
        # lr: 1.0e-4
    l_rate: 1.0e-3
    l_schedule:
    loss:
        name: "multi_scale_cross_entropy" #'cross_entropy'
        size_average: False
    lr_schedule:
    momentum: 0.99
    weight_decay: 0.0005
    resume: frrnB_cityscapes_best_model.pkl
    visdom: False
